### ISSUE TITLE
When I type: com c-x c-o gives me the following error

### ISSUE THREAD

**Issue by Xenorage** [huleiak47/vim-AHKcomplete#2]
When I type: com c-x c-o gives me the following error: (cygwin VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  4 2018 23:40:37)

Error detected while processing function ahkcomplete#Complete:                                                        │dos2unix: Skipping binary file ./ftplugin/autohotkey/__pycache__/ahkcomp.cpython-36.pyc
line   18:                                                                                                            │dos2unix: converting file ./LICENSE to Unix format...
Vim:Vim:Vim:Vim:Vim:Vim:Vim:Vim:Vim:Vim(call):E722: Missing comma in Dictionary: s event sources to functions with a g│dos2unix: converting file ./README.md to Unix format...
iven prefix.', 'icase':1})

**Comment by Xenorage** [comment]
using Python 3.6.4
Commented out the following line in ahkcomp.py
`
 print(str(e), file=sys.stderr)
`
Print function probably change in newer version
Have no clue about python, dont know how to fix it. Dont want to study it right now.
Well I wont get error messages but now it works.

**Comment by huleiak47** [comment]
remove `print(str(e), file=sys.stderr)` works.
I think it's because something changed in vim of new version, not `print` function changed. I'll remote the print line at next commit.
